services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql
    networks:
      - backend
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"


  api:
    image: ghcr.io/biblioteca-viva/backend:latest
    container_name: biblioteca-viva-api
    restart: unless-stopped
    ports:
      - "8080:8080" ##ajustar
    environment:
      SPRING_PROFILES_ACTIVE: "prod"
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
      CLOUDINARY_URL: ${CLOUDINARY_URL}
      RESEND_API_KEY: ${RESEND_API_KEY}
      RESEND_FROM_EMAIL: ${RESEND_FROM_EMAIL}
      PASSWORD_RESET_PEPPER: ${PASSWORD_RESET_PEPPER}
      COOKIE_SECURE: "true"
      COOKIE_SAME_SITE: "None"

    networks:
      - backend
    depends_on:
      db:
        condition: service_healthy

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  db_data:

networks:
  backend: