spring:
  application:
    name: backend
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/bibliotecaviva
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
        hibernate:
            format_sql: true
            dialect: org.hibernate.dialect.PostgreSQLDialect
scalar:
  enabled: true
  url: /v3/api-docs
  path: /scalar
  theme: saturn
springdoc:
  api-docs:
    path: /v3/api-docs

security:
  jwt:
    secret: 6269626c696f74656361766976612d736563726574a2d6b6579efabcdef01234
    expiration: 86400000
