spring:
  application:
    name: backend
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/bibliotecaviva
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
        hibernate:
            format_sql: true
            dialect: org.hibernate.dialect.PostgreSQLDialect